### ISSUE TITLE
2nd test fails due to a 404

### ISSUE THREAD

**Issue by MikeCook9994** [tinderjs/tinderauth#4]
I have the first test passing after setting the environment variables. I've grabbed my user id from the site provided in the readme however the 2nd test gets this outcome:

1) TEST should work:
   Error: Server returned status code 404 from https://www.facebook.com/intern/common/referer_frame.php
    at E:\cook\Documents\projects\tinderauth\node_modules\zombie\lib\document.js:713:39
    at process._tickCallback (internal/process/next_tick.js:103:7)

What can I do about a Page Not Found exception? I would take this to mean that my user id is wrong, but I don't know how. I have a tinder account and am using a valid facebook account as well.

**Comment by gregbarcza** [comment]
1. Do you use the latest version?
2. The readme is not corrent about getting your facebook id since it's different for every app.
   This is how you should get it:
   1. Go to https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token
   2. quickly copy the token
   3. go to `https://developers.facebook.com/tools/explorer/376029892466621` replace a token & hit submit
   4. you will find your tinder app specific id there!

**Comment by MikeCook9994** [comment]
1) Yup, I'm definitely on the most recent version.

2) I was definitely not doing this previously, but following your instructions gives me the same user id. I was my user id correct? Not tinder's app ID that I get by clicking the info bubble on the query bar on the tool?

Still getting the same result sadly.

**Comment by gregbarcza** [comment]
Can you ping me at [Slack](http://tinderjs.herokuapp.com/)? I will try to help you!

**Comment by mayeaux** [comment]
Thanks @barczaG . Also, @MikeCook9994 , if you write out the steps you take to generate that error step by step I will try and give you a hand as well.

**Comment by MikeCook9994** [comment]
Yesterday from my new machine:
1) Cloned the repo
2) npm install
3) npm install -g mocha
4) Sets the the username in password environment variables for the system (vs. user. This should not make a difference)?
5) Followed the steps in the original response to get my user id. Outcome was the same as from using the website provided in the readme.
6) Set the user id environment variable
7) npm test

First test passed as expected. Second test still got the 404 with the same error message.

Will ping on slack later. Currently at work without access to my machine.

**Comment by mayeaux** [comment]
I'm guessing the error is here: 

> 4) Sets the the username in password environment variables for the system (vs. user. This should not make a difference)?

Without telling me the data points obviously, can you explain to me what environment variables you are exporting? We can try and echo those from the terminal as well and see what we get back.

**Comment by MikeCook9994** [comment]
[Environment variables](http://i.imgur.com/2HLr0kw.png)

If it was an issues with the environment variables wouldn't the first test fail instead?

**Comment by gregbarcza** [comment]
I think the problem is that Facebook updated their system and login doesn't occur anymore on the oAuth dialog. (the trick is that they are doing this distributed deploying stuff so for some region it still works/worked) I will post a fix soon!
![screenshot 2016-08-10 10 48 04](https://cloud.githubusercontent.com/assets/1392454/17547565/315ac9b2-5ee8-11e6-9ba9-f62aac2ec076.png)

**Comment by MikeCook9994** [comment]
Thank you! I'll check back periodically. Thankfully there's things I can do in the mean time that keep me from being blocked.

**Comment by gregbarcza** [comment]
The fix is harder then I thought, in the new version `access_token` is coming from an ajax response and I'm not sure It can be captured with Zombie.js maybe we have to use PhantomJs 😕

**Comment by gregbarcza** [comment]
https://github.com/tinderjs/tinderauth/pull/5

**Comment by Shanelle** [comment]
Warning
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

**Comment by Shanelle** [comment]
![image](https://cloud.githubusercontent.com/assets/8592519/21739503/7f55eaec-d4d7-11e6-810d-1f1ea4fe011e.png)
